### ISSUE TITLE
Visual Studio Winforms style Editor and Drag and drop gallery planned?

### ISSUE THREAD

**Issue by TheColonel2688** [modern-forms/Modern.Forms#17]
Visual Studio Winforms style Editor and Drag and drop gallery planned?

This is not so much a question of my wants, but I am trying to convince the Developer of AdvancedHMI to port his code from Wibforms to something cross platform. His biggest hang up is no visual editing support with Avalonia.

The user base for the software is mostly non programmers.

**Comment by jpobst** [comment]
That's a very common question, so I went ahead and made an enhancement issue for it: https://github.com/modern-forms/Modern.Forms/issues/18.  As stated there, a visual editor is probably not happening any time soon due to other priorities.

While I do not have experience with it, Avalonia does have a visual editor: https://avaloniaui.net/docs/quickstart/vs-designer that might be worth checking out.

**Comment by TheColonel2688** [comment]
As far as I know, the Avalonia VS-Designer is just a preview tool, it doesn't let you do a complete design visually. :/

Thank I understand. Can actual true visual designing be clarified in the issue. I know it is will be way off.

**Comment by jpobst** [comment]
Sure! I added "drag and drop" to it to clarify.

**Comment by TheColonel2688** [comment]
Thank you!!!
