### ISSUE TITLE
Changing TabPage by reference

### ISSUE THREAD

**Issue by dax-leo** [modern-forms/Modern.Forms#58]
Hi,

changing object reference to TabPage collection is not working properly.
https://github.com/modern-forms/Modern.Forms/blob/ab486679ef329dd9849a3d2db0483b389d249e54/samples/ControlGallery/Panels/TabControlPanel.cs#L32

Page is shown empty.
![image](https://github.com/modern-forms/Modern.Forms/assets/70173560/30353269-9d12-4c26-aecd-8776b679ee10)

Maybe it would be good to remove this from ControlGallery example and suggest using only .Add() or Remove()/Insert() when changing tab pages ?

**Comment by jpobst** [comment]
It looks like this issue is deeper than just `TabControl`.  When a `Control` is set in any `ControlCollection` using the indexer the usual `Insert` logic is bypassed.

https://github.com/modern-forms/Modern.Forms/blob/ab486679ef329dd9849a3d2db0483b389d249e54/src/Modern.Forms/ControlCollection.cs#L462

Likely this was broken when the `System.Windows.Forms.Layout` code was imported from Winforms.

**Comment by jpobst** [comment]
I think https://github.com/modern-forms/Modern.Forms/pull/60 will fix it.
